# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "pypy"

# Here we install the ubuntu dependencies with apt-get.
before_install:
  - sudo apt-get update
  - sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python-numpy libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libx11-6 libX11-dev xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic ipython python-opencv python-scipy python-numpy python-pygame

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - pip install coverage coveralls

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage

after_success:
    coveralls