# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "pypy"

# Here we install the ubuntu dependencies with apt-get.
before_install:
  - sudo apt-get update
  - sudo apt-get install python-numpy python-nose python-imaging python-scipy python-pygame
  - sudo apt-get install libcv2.3 libcvaux2.3 libhighgui2.3 python-opencv libcv-dev libcvaux-dev libhighgui-dev

virtualenv:
  system_site_packages: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - pip install coverage coveralls

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage

after_success:
    coveralls